--CHECAGEM DE INFORMAÇÕES
SELECT * FROM pais;


--ALTERAÇÕES NAS TABELAS
ALTER TABLE CIDADE MODIFY  NOM_CIDADE VARCHAR2(50);
ALTER TABLE PEDIDO ADD STATUS VARCHAR2(50);


-- INSERTS DE INFORMAÇÕES NAS TABELAS
INSERT INTO PAIS SELECT * FROM PF1788.PAIS;
COMMIT;

INSERT INTO ESTADO SELECT * FROM PF1788.ESTADO;
COMMIT;

INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
COMMIT;

INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
COMMIT;

INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
COMMIT;

INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
COMMIT;

INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
COMMIT;

INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
COMMIT;

INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
COMMIT;

INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
COMMIT;

INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
COMMIT;

INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
COMMIT;

INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
COMMIT;

INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
COMMIT;

INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
COMMIT;

INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
COMMIT;

INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
COMMIT;

INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;
COMMIT;

/*
ATIVIDADE

Criar uma consulta em SQL que traga o endereço completo do cliente
com os seguintes atributos:
- ID_CLIENTE (F)
- NOME_CLIENTE (F)
- TIPO DE CLIENTE (F)
- ENDERECO_COMPLETO (F)
- CEP (F)
- NOME CIDADE
- NOME ESTADO
- NOME PAIS
*/

-- RESOLUÇÃO
SELECT 
    --ID_CLIENTE
    cli.COD_CLIENTE "Código Cliente",  
    --NOME_CLIENTE
    cli.NOM_CLIENTE "Nome Cliente",
    --TIPO DE CLIENTE
    cli.TIP_PESSOA "Tipo Cliente (fisica ou juridica)",
    
    --ENDEREÇO COMPLETO
    DES_ENDERECO "Rua", 
    NUM_ENDERECO "Numero",
    DES_COMPLEMENTO "Complemento",
    --CEP
    NUM_CEP "CEP",
    --NOME BAIRRO
    DES_BAIRRO "Bairro",
    --NOME CIDADE
    NOM_CIDADE "Cidade",
    --NOME ESTADO
    NOM_ESTADO "ESTADO",
    --NOME PAIS
    NOM_PAIS "PAIS"
FROM 
    ENDERECO_CLIENTE end 
JOIN CLIENTE cli ON end.COD_CLIENTE = cli.COD_CLIENTE
JOIN CIDADE cd ON end.COD_CIDADE = cd.COD_CIDADE
JOIN ESTADO est ON cd.COD_ESTADO = est.COD_ESTADO
JOIN PAIS ps ON est.COD_PAIS = ps.COD_PAIS;

